### ISSUE TITLE
src variable in get_places needs to be set in local config file, not hard coded in script

### ISSUE THREAD

**Issue by ericlenning** [tjturnage/pyart#6]
The variable "src" in the get_places function is hard coded to a path pointing to GIS data.  This path needs to be specified in the gis_dir variable through the local config file.

**Comment by tjturnage** [comment]
Looks like there is something in local config already to define this. Should this issues still be open?

**Comment by ericlenning** [comment]
The pyart_plot.py code hasn't been updated to take advantage of the variable in local config, nor does the local config provide the full pathname of the places csv file.  We don't want to hard-code ../places/places_conus.csv as the only option for the places filename.
